### ISSUE TITLE
在服务提供者中加载路由，在未使用到路由的项目中，会导致 `boot` 严重慢

### ISSUE THREAD

**Issue by xiaohuilam** [mingyoung/easywechat-composer#11]
在服务提供者中加载路由，在未使用到路由的项目中，会导致 `boot` 严重慢
https://github.com/mingyoung/easywechat-composer/blob/e0a24198ab5f8c58c867d25978c86624730a5cf6/src/Laravel/ServiceProvider.php#L23-L32

在核心代码中不必指定 declare(strict_types=1);
https://github.com/mingyoung/easywechat-composer/blob/e0a24198ab5f8c58c867d25978c86624730a5cf6/src/Laravel/ServiceProvider.php#L1-L3

使用 composer.lock 的哈希作为 key，一方面是安全性可能被枚举到。另外就是性能上，会多一次文件io。再如果项目的 composer.lock 被删除了，会报错？
https://github.com/mingyoung/easywechat-composer/blob/e0a24198ab5f8c58c867d25978c86624730a5cf6/src/Laravel/ServiceProvider.php#L44-L60

**Comment by mingyoung** [comment]
谢谢提醒！

> 在服务提供者中加载路由，在未使用到路由的项目中，会导致 `boot` 严重慢

这里未使用到路由的项目是指什么项目？

**Comment by xiaohuilam** [comment]
@mingyoung

就是用 `easywechat` 的微信支付功能，而不用公共号接受用户事件/消息时，加载这些路由的时间消耗是比较大的。
具体等我写个 benchmark 集中压测下。

**Comment by mingyoung** [comment]
了解，现在已经去掉了 Auto-Discovery。用户需要用到再手动加载
