### ISSUE TITLE
Laravel 5.8 缓存存活时间问题

### ISSUE THREAD

**Issue by monyxie** [mingyoung/easywechat-composer#16]
Laravel 5.8 的缓存存活时间单位从分钟变成了秒，造成 `EasyWeChatComposer\Laravel\ServiceProvider::getMd5Key()` 的行为在 Laravel 5.8 之前和之后不一致。

**Comment by mingyoung** [comment]
这个会导致什么问题？频繁读取文件？

**Comment by monyxie** [comment]
理论上说是的，但是在我自己的实际使用情形下对性能的影响并不大。但是也不能排除会有其他会受较大影响的情形。
况且抛开实际的影响不谈，确保程序实际的行为跟预期的行为一致不是比较好吗？

**Comment by mingyoung** [comment]
#17 已修改，感谢指出
