### ISSUE TITLE
overtrue/wechat 在 composer 2 时，无法安装了

### ISSUE THREAD

**Issue by mouyong** [mingyoung/easywechat-composer#19]
![image](https://user-images.githubusercontent.com/10336437/98059331-c6cefb00-1e81-11eb-9ee0-9ff6c15c1580.png)

**Comment by mingyoung** [comment]
更新一下包？五月份已经兼容 Composer 2.x

**Comment by mouyong** [comment]
overtrue/wechat 这个包，不敢更新

**Comment by mingyoung** [comment]
composer u easywechat-composer/easywechat-composer 试试？

**Comment by mouyong** [comment]
https://github.com/overtrue/wechat/blob/4.2.35/composer.json#L23 考虑给他加个版本号不 

overtrue/wechat:4.2.36 依赖新的 easywechat-composer 版本

**Comment by mingyoung** [comment]
没必要吧，都是 1.x 的🤔

**Comment by mouyong** [comment]
![image](https://user-images.githubusercontent.com/10336437/98059839-0ea25200-1e83-11eb-8a66-0f503f1a73ef.png)

好像可以了。
